#if defined _included_plague_human_const
    #endinput
#endif

#define _included_plague_human_const

enum HumanAttributes {
    any:Human_Health,
    any:Human_Gravity,
    any:Human_SpeedAdd,
    any:Human_Painshock,
    any:Human_Flags,
    any:Human_MenuShow
};

enum HumanInformation {
    any:Human_SystemName,
    any:Human_Name,
    any:Human_Model,
    any:Human_SoundsPain,
    any:Human_SoundsDie
};