#if defined _included_plague_zombie_const
    #endinput
#endif

#define _included_plague_zombie_const

enum ZombieAttributes {
    any:Zombie_Health,
    any:Zombie_Gravity,
    any:Zombie_SpeedAdd,
    any:Zombie_Knockback,
    any:Zombie_Painshock,
    any:Zombie_Flags,
    any:Zombie_MenuShow,
    any:Zombie_AttackDamage,
    any:Zombie_Attack2Damage,
    any:Zombie_AttackDelay, 
    any:Zombie_AttackDelay2,
    any:Zombie_Attack2Delay, 
    any:Zombie_Attack2Delay1,
    any:Zombie_AttackDelayMiss, 
    any:Zombie_AttackDelayMiss2,
    any:Zombie_Attack2DelayMiss, 
    any:Zombie_Attack2DelayMiss1,
    any:Zombie_AttackDistance,
    any:Zombie_Attack2Distance,
};

enum ZombieInformation {
    any:Zombie_SystemName,
    any:Zombie_Name,
    any:Zombie_Model,
    any:Zombie_ClawModel,
    any:Zombie_SoundsPain,
    any:Zombie_SoundsSpawn,
    any:Zombie_SoundsDie
};